
import type { Child } from '@prisma/client';

export type Program = 'Infant (0-12months)' | 'Toddler (1 to 3 years)' | 'Preschool (3 to 5 years)' | 'Gradeschooler (5 to 12 years)';
export const programOptions: Program[] = ['Infant (0-12months)', 'Toddler (1 to 3 years)', 'Preschool (3 to 5 years)', 'Gradeschooler (5 to 12 years)'];

export type ProgramType = 'Full time' | 'Part time' | 'Ad-hoc daily basis';
export const programTypeOptions: ProgramType[] = ['Full time', 'Part time', 'Ad-hoc daily basis'];

export type ChildStatus = 'Active' | 'Waitlisted' | 'Inactive';

export const initialEnrolledChildren: Child[] = [
  {
    id: 'child_1',
    name: 'Olivia Martin',
    dateOfBirth: new Date('2021-05-20'),
    startDate: new Date('2023-09-01'),
    program: 'Preschool (3 to 5 years)',
    programType: 'Full time',
    status: 'Active',
    motherName: 'Sophia Martin',
    fatherName: 'Benjamin Martin',
    homePhone: '(555) 111-2222',
    mobilePhone: '(555) 333-4444',
    address: '123 Maple St, Vancouver, BC',
    emergencyName: 'Emily White',
    emergencyPhone: '(555) 555-6666',
    vaccination: 'Up to date.',
    allergies: 'None',
    notes: 'Loves painting and story time.',
    photoUrl: 'https://placehold.co/100x100.png',
    photoHint: 'young girl',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'child_2',
    name: 'Liam Garcia',
    dateOfBirth: new Date('2022-11-10'),
    startDate: new Date('2024-01-15'),
    program: 'Toddler (1 to 3 years)',
    programType: 'Full time',
    status: 'Active',
    motherName: 'Isabella Garcia',
    fatherName: 'Mateo Garcia',
    homePhone: null,
    mobilePhone: '(555) 777-8888',
    address: '456 Oak Ave, Burnaby, BC',
    emergencyName: 'Lucas Hernandez',
    emergencyPhone: '(555) 999-0000',
    vaccination: 'Up to date.',
    allergies: 'Peanuts',
    notes: 'EpiPen is in his bag.',
    photoUrl: 'https://placehold.co/100x100.png',
    photoHint: 'toddler boy',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'child_3',
    name: 'Noah Hernandez',
    dateOfBirth: new Date('2023-08-01'),
    startDate: new Date('2024-09-01'),
    program: 'Infant (0-12months)',
    programType: 'Full time',
    status: 'Waitlisted',
    motherName: 'Mia Hernandez',
    fatherName: 'Lucas Hernandez',
    homePhone: '(555) 121-2121',
    mobilePhone: '(555) 343-4343',
    address: '789 Pine Ln, Surrey, BC',
    emergencyName: 'Isabella Garcia',
    emergencyPhone: '(555) 777-8888',
    vaccination: 'Scheduled',
    allergies: 'None known',
    notes: 'Naps twice a day.',
    photoUrl: 'https://placehold.co/100x100.png',
    photoHint: 'baby boy',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'child_4',
    name: 'Emma Rodriguez',
    dateOfBirth: new Date('2020-03-15'),
    startDate: new Date('2022-09-01'),
    program: 'Gradeschooler (5 to 12 years)',
    programType: 'Part time',
    status: 'Inactive',
    motherName: 'Ava Rodriguez',
    fatherName: 'William Rodriguez',
    homePhone: '(555) 565-6565',
    mobilePhone: '(555) 787-8787',
    address: '101 Birch Rd, Richmond, BC',
    emergencyName: 'Grandma Rodriguez',
    emergencyPhone: '(555) 111-1111',
    vaccination: 'Up to date.',
    allergies: 'None',
    notes: 'Graduated from program.',
    photoUrl: 'https://placehold.co/100x100.png',
    photoHint: 'school girl',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
